"""
Angle-Set Ring (Cam Ring) — 6061-T6 Aluminium, Type II anodized.

Upper face: dual-spiral open-face cam track (generated by cad/utils/cam_geometry.py).
Lower face: knurled grip + laser-etched angle labels (48 / 60 / 80) at 60° spacing.
Outer rim: 3× detent dimples at 60° spacing.

Origin: ring center at (0, 0, 0), +Z = up toward shells.
Material: params.CAM_RING_MATERIAL
Drawing note: "mask detent dimples before anodize" — see manufacturing/surface_finish_notes.md
"""
from __future__ import annotations

import math

try:
    import cadquery as cq
except ImportError:
    cq = None  # type: ignore

import cad.params as _default_params
from cad.utils.cam_geometry import CamTrackPoint, cam_track_for_preset_radii


def _polar_to_xy(angle_deg: float, radius_mm: float) -> tuple[float, float]:
    """Convert a polar cam-track point into XY workplane coordinates."""
    angle_rad = math.radians(angle_deg)
    return (radius_mm * math.cos(angle_rad), radius_mm * math.sin(angle_rad))


def _sample_track_points(track: list[CamTrackPoint], min_spacing_mm: float) -> list[tuple[float, float]]:
    """
    Down-sample densely generated cam-track points while preserving overlap.

    The cam utility emits many closely spaced samples. For the V1 solid model we cut the
    track as a swept-equivalent pocket built from a sketched union of circles; sampling by
    minimum XY spacing keeps the shape honest while avoiding an unnecessarily heavy BREP.
    """
    if not track:
        return []

    sampled: list[tuple[float, float]] = []
    last_xy: tuple[float, float] | None = None

    for point in track:
        xy = _polar_to_xy(point.angle_deg, point.radius_mm)
        if last_xy is None:
            sampled.append(xy)
            last_xy = xy
            continue

        dx = xy[0] - last_xy[0]
        dy = xy[1] - last_xy[1]
        if math.hypot(dx, dy) >= min_spacing_mm:
            sampled.append(xy)
            last_xy = xy

    final_xy = _polar_to_xy(track[-1].angle_deg, track[-1].radius_mm)
    if math.hypot(sampled[-1][0] - final_xy[0], sampled[-1][1] - final_xy[1]) > 1e-6:
        sampled.append(final_xy)

    return sampled


def _cut_track_lane(ring, lane_points: list[tuple[float, float]], params, top_z: float):
    """Cut one open-face cam lane into the ring from the +Z side."""
    if not lane_points:
        return ring

    lane_profile = cq.Sketch().push(lane_points).circle(params.CAM_TRACK_WIDTH_MM / 2.0)
    lane_cutter = (
        cq.Workplane("XY", origin=(0.0, 0.0, top_z - params.CAM_TRACK_DEPTH_MM))
        .placeSketch(lane_profile)
        .extrude(params.CAM_TRACK_DEPTH_MM)
    )
    return ring.cut(lane_cutter)


def build(params=None):  # -> cq.Workplane
    """
    Build the Cam Ring.

    Modelled geometry:
        - annular ring body
        - open-face dual cam track on +Z face
        - 3 detent dimples on the outer rim

    Not modelled as geometry:
        - grip knurl on the user-facing face
        - laser-etched angle labels
        - separate track-entry chamfer detail (leave for a later drawing/geometry pass)
    """
    if params is None:
        params = _default_params

    if cq is None:
        raise RuntimeError("CadQuery is not installed.")

    outer_radius = params.CAM_RING_OD_MM / 2.0
    bore_radius = params.CAM_RING_BORE_MM / 2.0
    half_thickness = params.CAM_RING_THICKNESS_MM / 2.0
    top_z = half_thickness

    # Base annular body centered on origin.
    ring = (
        cq.Workplane("XY")
        .circle(outer_radius)
        .circle(bore_radius)
        .extrude(half_thickness, both=True)
    )

    # Cam track: model as a union of overlapping cylindrical pockets sampled along the
    # tested polar path. This is simpler and more robust than a swept slot at this stage,
    # while still producing the correct functional open-face groove envelope.
    track_l, track_r = cam_track_for_preset_radii(params)
    track_l_points = _sample_track_points(track_l, params.CAM_TRACK_WIDTH_MM * 0.5)
    track_r_points = _sample_track_points(track_r, params.CAM_TRACK_WIDTH_MM * 0.5)
    ring = _cut_track_lane(ring, track_l_points, params, top_z)
    ring = _cut_track_lane(ring, track_r_points, params, top_z)

    # Detent dimples: spherical pockets on the outer rim, biased into the lower half of
    # the ring so the user-facing underside remains the detent interface zone.
    detent_center_radius = outer_radius + params.DETENT_DIMPLE_RADIUS_MM - params.DETENT_DIMPLE_DEPTH_MM
    detent_z = -half_thickness / 2.0

    for idx in range(params.DETENT_POSITIONS):
        angle_deg = idx * params.DETENT_SPACING_DEG
        x, y = _polar_to_xy(angle_deg, detent_center_radius)
        dimple_cutter = cq.Workplane("XY", origin=(x, y, detent_z)).sphere(params.DETENT_DIMPLE_RADIUS_MM)
        ring = ring.cut(dimple_cutter)

    return ring
